weights: C:\FYP\python\fyp_servers\retraining_server/weights/bus_stop/bus_stop.pt
cfg: ''
data: C:\FYP\python\fyp_servers\retraining_server/training_dataset/bus_stop/data.yaml
hyp: yolov5-master\data\hyps\hyp.scratch-low.yaml
epochs: 10
batch_size: 1
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: C:\FYP\python\fyp_servers\retraining_server/weights/bus_stop
name: bus_stop
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
seed: 0
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
img: 640
save_dir: C:\FYP\python\fyp_servers\retraining_server\weights\bus_stop\bus_stop
